// <auto-generated />
using System;
using CucineCRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CucineCRM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007102100_AggiungiAccountCliente")]
    partial class AggiungiAccountCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CucineCRM.Domain.Entities.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaManagerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Zona");

                    b.ToTable("Agenti", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Attivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completata")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("Priorita")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PromemoriaMinutiPrima")
                        .HasColumnType("text");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoAttivita")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataScadenza");

                    b.HasIndex("UtenteId");

                    b.HasIndex("Completata", "DataScadenza");

                    b.ToTable("Attivita", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Azione")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<int>("EntitaId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeEntita")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataCreazione");

                    b.HasIndex("UtenteId");

                    b.HasIndex("NomeEntita", "EntitaId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Calendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttivitaId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleEventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SincronizzatoConGoogle")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UltimaSincronizzazione")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaId")
                        .IsUnique();

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataEvento");

                    b.ToTable("Calendario", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenteId")
                        .HasColumnType("integer");

                    b.Property<string>("CAP")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Citta")
                        .HasColumnType("text");

                    b.Property<string>("CodiceCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("text");

                    b.Property<string>("PartitaIVA")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PercentualeProvvigione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Regione")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("CodiceCliente")
                        .IsUnique();

                    b.HasIndex("Provincia");

                    b.HasIndex("Regione");

                    b.ToTable("Clienti", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Comunicazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Contenuto")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("DimensioneByte")
                        .HasColumnType("bigint");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("TipoContenuto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UtentePubblicazioneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataCreazione");

                    b.HasIndex("UtentePubblicazioneId");

                    b.ToTable("Comunicazioni", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Fornitore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasFilter("\"Eliminato\" = false");

                    b.ToTable("Fornitori", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Importazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completata")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataImportazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("LogEsito")
                        .HasColumnType("text");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("PeriodoCompetenza")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("RigheDuplicate")
                        .HasColumnType("integer");

                    b.Property<int>("RigheImportate")
                        .HasColumnType("integer");

                    b.Property<int>("RighePlesse")
                        .HasColumnType("integer");

                    b.Property<int>("RigheScartate")
                        .HasColumnType("integer");

                    b.Property<int>("UtenteImportazioneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataImportazione");

                    b.HasIndex("PeriodoCompetenza");

                    b.HasIndex("UtenteImportazioneId");

                    b.ToTable("Importazioni", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.NotaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UtenteId");

                    b.ToTable("NoteCliente", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Notifica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataLettura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<bool>("Letta")
                        .HasColumnType("boolean");

                    b.Property<string>("Messaggio")
                        .HasColumnType("text");

                    b.Property<int?>("RiferimentoEntitaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId", "Letta");

                    b.ToTable("Notifiche", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.ObiettivoVendita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenteId")
                        .HasColumnType("integer");

                    b.Property<int>("Anno")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<int>("Mese")
                        .HasColumnType("integer");

                    b.Property<int>("ObiettivoCucine")
                        .HasColumnType("integer");

                    b.Property<decimal>("ObiettivoFatturato")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId", "Mese", "Anno")
                        .IsUnique();

                    b.ToTable("ObiettiviVendita", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<int>("FornitoreId")
                        .HasColumnType("integer");

                    b.Property<int?>("ImportazioneId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("NumeroComplementi")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCucine")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroElettrodomestici")
                        .HasColumnType("integer");

                    b.Property<string>("RiferimentoEsterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatoOrdine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataOrdine");

                    b.HasIndex("FornitoreId");

                    b.HasIndex("ImportazioneId");

                    b.HasIndex("RiferimentoEsterno")
                        .IsUnique()
                        .HasFilter("\"RiferimentoEsterno\" IS NOT NULL AND \"Eliminato\" = false");

                    b.ToTable("Ordini", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.StoricoKPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenteId")
                        .HasColumnType("integer");

                    b.Property<int>("Anno")
                        .HasColumnType("integer");

                    b.Property<int>("CucineVendute")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Fatturato")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Mese")
                        .HasColumnType("integer");

                    b.Property<int>("NuoviClienti")
                        .HasColumnType("integer");

                    b.Property<decimal>("OrdineMedio")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("Mese", "Anno", "AgenteId")
                        .IsUnique();

                    b.ToTable("StoricoKPI", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenteId")
                        .HasColumnType("integer");

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("GoogleRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GoogleTokenScadenza")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasFilter("\"ClienteId\" IS NOT NULL AND \"Eliminato\" = false");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Ruolo");

                    b.ToTable("Utenti", (string)null);
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Agente", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Agente", "AreaManager")
                        .WithMany("AgentiGestiti")
                        .HasForeignKey("AreaManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaManager");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Attivita", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Attivita")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CucineCRM.Domain.Entities.Utente", "Utente")
                        .WithMany("Attivita")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Calendario", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Attivita", "Attivita")
                        .WithOne("EventoCalendario")
                        .HasForeignKey("CucineCRM.Domain.Entities.Calendario", "AttivitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CucineCRM.Domain.Entities.Cliente", "Cliente")
                        .WithMany("EventiCalendario")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attivita");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Agente", "Agente")
                        .WithMany("Clienti")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Comunicazione", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Utente", "UtentePubblicazione")
                        .WithMany("Comunicazioni")
                        .HasForeignKey("UtentePubblicazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtentePubblicazione");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Importazione", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Utente", "UtenteImportazione")
                        .WithMany("Importazioni")
                        .HasForeignKey("UtenteImportazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtenteImportazione");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.NotaCliente", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Note")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CucineCRM.Domain.Entities.Utente", "Utente")
                        .WithMany("Note")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Notifica", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.ObiettivoVendita", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Agente", "Agente")
                        .WithMany("Obiettivi")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Ordine", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ordini")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CucineCRM.Domain.Entities.Fornitore", "Fornitore")
                        .WithMany("Ordini")
                        .HasForeignKey("FornitoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CucineCRM.Domain.Entities.Importazione", "Importazione")
                        .WithMany("Ordini")
                        .HasForeignKey("ImportazioneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Fornitore");

                    b.Navigation("Importazione");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.StoricoKPI", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Utente", b =>
                {
                    b.HasOne("CucineCRM.Domain.Entities.Agente", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CucineCRM.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Agente", b =>
                {
                    b.Navigation("AgentiGestiti");

                    b.Navigation("Clienti");

                    b.Navigation("Obiettivi");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Attivita", b =>
                {
                    b.Navigation("EventoCalendario");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Attivita");

                    b.Navigation("EventiCalendario");

                    b.Navigation("Note");

                    b.Navigation("Ordini");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Fornitore", b =>
                {
                    b.Navigation("Ordini");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Importazione", b =>
                {
                    b.Navigation("Ordini");
                });

            modelBuilder.Entity("CucineCRM.Domain.Entities.Utente", b =>
                {
                    b.Navigation("Attivita");

                    b.Navigation("Comunicazioni");

                    b.Navigation("Importazioni");

                    b.Navigation("Note");
                });
#pragma warning restore 612, 618
        }
    }
}
